ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'AMAZON_ADS_CAMPAIGN_APPROVAL';
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'AMAZON_ADS_BUDGET_CHANGE_APPROVAL';
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'AMAZON_ADS_REPORT_ACKNOWLEDGEMENT';
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'AMAZON_ADS_STRATEGY_APPROVAL';
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'AMAZON_ADS_CREATIVE_APPROVAL';
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'AMAZON_ADS_PRODUCT_PROMOTION_APPROVAL';
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'AMAZON_ADS_SEARCH_TERM_ACTION_APPROVAL';
