-- AlterEnum
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'GOOGLE_ADS_CAMPAIGN_APPROVAL';

-- AlterEnum
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'GOOGLE_ADS_BUDGET_CHANGE_APPROVAL';

-- AlterEnum
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'GOOGLE_ADS_REPORT_ACKNOWLEDGEMENT';

-- AlterEnum
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'GOOGLE_ADS_STRATEGY_APPROVAL';

-- AlterEnum
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'GOOGLE_ADS_CREATIVE_APPROVAL';

-- AlterEnum
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'GOOGLE_ADS_KEYWORD_PLAN_APPROVAL';
