export interface PackageTier {
  key: string;
  name: string;
  description: string;
  features: string[];
  defaultPrice: number | null;
  priceSuffix: string;
  badge?: string;
  isCustomPrice: boolean;
}

export interface ServiceCatalogEntry {
  serviceKey: string;
  label: string;
  tiers: PackageTier[];
}

export const SERVICE_CATALOG: ServiceCatalogEntry[] = [
  {
    serviceKey: "GROWTH_HUB",
    label: "Growth Hub",
    tiers: [
      {
        key: "LAUNCH",
        name: "Launch Paketi",
        description: "İşletmenizi dijital dönüşümün ilk adımına atlatın. Sosyal medya ve yönetimi, pazarlama dünyasına girişinizi yapın.",
        features: [
          "Strateji & kurulum",
          "Sosyal medya yönetimi (2 kanal)",
          "Reklam ve performans (9.000 ₺ max bütçe)",
          "Tasarım desteği (4 tasarım)",
          "Aylık raporlama",
        ],
        defaultPrice: 34000,
        priceSuffix: "/ ay",
        isCustomPrice: false,
      },
      {
        key: "GROWTH",
        name: "Growth Paketi",
        description: "Dijitalde var olmak yetmez, büyümek gerekir. Sosyal medya ve reklam süreçlerinizi ölçeklenebilir hale getirin.",
        features: [
          "Strateji ve yönetim",
          "Sosyal medya yönetimi (3 kanal)",
          "16 içerik + performans takibi",
          "Reklam yönetimi",
          "Tasarım ve kreatif destek",
          "Web dönüşüm desteği",
          "Raporlama ve iletişim",
        ],
        defaultPrice: 49000,
        priceSuffix: "/ ay",
        badge: "En Çok Tercih Edilen",
        isCustomPrice: false,
      },
      {
        key: "SCALE",
        name: "Scale Paketi",
        description: "Artık sadece büyümek değil, büyümeyi yönetmek gerekiyor. Scale paketi markanız için sürdürülebilir ölçekleme sunar.",
        features: [
          "Özel büyüme stratejisi",
          "Genişletilmiş kanal yönetimi",
          "Gelişmiş reklam & performans yönetimi",
          "İleri seviye içerik & kreatif süreçler",
          "Dönüşüm & sistem optimizasyonu",
          "Stratejik iletişim & yönetim",
        ],
        defaultPrice: null,
        priceSuffix: "",
        isCustomPrice: true,
      },
    ],
  },
  {
    serviceKey: "SOCIAL_MEDIA",
    label: "Sosyal Medya Yönetimi",
    tiers: [
      {
        key: "SOCIAL_START",
        name: "Social Start Paketi",
        description: "İşletmenizin sosyal medyadaki ilk adımını sağlam atması için tasarlandı.",
        features: [
          "Platform seçimi & kurulum",
          "Aylık içerik planı (12-16 post)",
          "Görsel tasarım (şablon + markaya uygun)",
          "Caption & hashtag stratejisi",
          "Haftalık paylaşım",
          "Temel DM & yorum takibi",
          "Aylık performans özeti",
        ],
        defaultPrice: 17499,
        priceSuffix: "/ ay",
        isCustomPrice: false,
      },
      {
        key: "SOCIAL_PRO",
        name: "Social Pro Paketi",
        description: "Sosyal medya ve içerik süreçlerinizi büyüme odaklı bir sisteme dönüştürür.",
        features: [
          "Social Start içeriğinin tamamı",
          "Aylık 20-24 içerik",
          "Reel & video içerik kurgusu",
          "Etkileşim odaklı içerik konseptleri",
          "DM & yorum yönetimi",
          "Rakip & trend analizi",
          "Story paylaşımları",
          "Aylık detaylı rapor",
        ],
        defaultPrice: 27500,
        priceSuffix: "/ ay",
        badge: "En çok tercih edilen",
        isCustomPrice: false,
      },
      {
        key: "SOCIAL_BRAND",
        name: "Social Brand+ Plus",
        description: "Marka algısı, itibar ve sürdürülebilir büyüme için tasarlandı.",
        features: [
          "Social Pro içeriğinin tamamı",
          "Aylık 30+ içerik",
          "Story & highlight yönetimi",
          "Kriz & itibar yönetimi",
          "Influencer / iş birliği danışmanlığı",
          "Reklam içeriği için kreatif destek",
          "Haftalık performans takibi",
          "Aylık strateji toplantısı",
        ],
        defaultPrice: null,
        priceSuffix: "",
        isCustomPrice: true,
      },
    ],
  },
  {
    serviceKey: "META_ADS",
    label: "Meta Ads",
    tiers: [
      {
        key: "META_START",
        name: "Marka Bilinirliği Paketi",
        description: "Meta Ads'e yeni başlayanlar veya küçük bütçeyle deneme yapmak isteyen markalar.",
        features: [
          "Meta Business & Ads hesabı kurulumu",
          "Kampanya + temel funnel yapısı",
          "2-3 kreatif test süreci",
          "Temel hedef kitle ayarları",
          "Pixel & dönüşüm kontrolü",
          "Aylık performans raporu",
          "Aylık raporlama (Reklam ve Strateji)",
        ],
        defaultPrice: 14900,
        priceSuffix: "/ ay",
        isCustomPrice: false,
      },
      {
        key: "META_GROWTH",
        name: "Satış Odaklı Büyüme Paketi",
        description: "Dijitalde var olmak yetmez; büyümek gerekir. Reklam süreçlerinizi ölçeklenebilir hale getirir.",
        features: [
          "Gelişmiş kampanya & funnel kurulumu",
          "A/B testli kreatif ve hedef kitle yapısı",
          "Haftalık optimizasyon ve bütçe yönetimi",
          "Meta Pixel & event optimizasyonu",
          "Detaylı performans takibi",
          "Haftalık not + aylık detaylı rapor",
          "2 haftada bir online toplantı",
        ],
        defaultPrice: 27500,
        priceSuffix: "/ ay",
        badge: "En çok tercih edilen",
        isCustomPrice: false,
      },
      {
        key: "META_SCALE",
        name: "Reklam Performans+ Paketi",
        description: "ROAS & ölçekleme odaklı yüksek bütçeli markalar için ideal paket.",
        features: [
          "Çok kampanyalı gelişmiş yapı",
          "Funnel bazlı reklam stratejisi",
          "Sürekli kreatif & copy testleri",
          "Günlük optimizasyon & ölçekleme",
          "ROAS ve CPA odaklı bütçe yönetimi",
          "Özel dashboard & ileri seviye raporlama",
        ],
        defaultPrice: null,
        priceSuffix: "",
        isCustomPrice: true,
      },
    ],
  },
  {
    serviceKey: "MEDIA_HUB",
    label: "Medya Hub (Tüm Reklamlar)",
    tiers: [
      {
        key: "MEDIA_HUB",
        name: "Medya Hub Paketi",
        description: "Dijitalde var olmak yetmez; büyümek gerekir. Reklam süreçlerinizi ölçeklenebilir hale getirir.",
        features: [
          "Meta + Google + TikTok + Amazon Ads yönetimi",
          "Kanal bazlı strateji planlama",
          "Funnel & dönüşüm yapısı",
          "Kreatif & metin yönlendirme",
          "A/B testleri",
          "Haftalık optimizasyon",
          "Pixel & event entegrasyonları",
          "Tek panel performans takibi",
          "Tek genel performans raporu",
          "1 haftalık öncelikli strateji toplantısı",
        ],
        defaultPrice: 39000,
        priceSuffix: "/ ay",
        badge: "Tek paket tüm reklamlar",
        isCustomPrice: false,
      },
    ],
  },
  {
    serviceKey: "GOOGLE_ADS",
    label: "Google Ads",
    tiers: [
      {
        key: "GOOGLE_START",
        name: "Marka Bilinirliği Paketi",
        description: "Yeni başlayanlar ve küçük işletmeler için ideal paket.",
        features: [
          "Google Ads & Google Business hesabı kurulumu",
          "Search kampanyası (marka + temel anahtar kelimeler)",
          "Temel metin & uzantı yapılandırması",
          "Temel anahtar kelime & rakip analizi",
          "Negatif anahtar kelime kurulumu",
          "Temel dönüşüm takibi",
          "Aylık performans raporu",
        ],
        defaultPrice: 12500,
        priceSuffix: "/ proje",
        isCustomPrice: false,
      },
      {
        key: "GOOGLE_GROWTH",
        name: "Satış Odaklı Büyüme Paketi",
        description: "Satış, form veya lead odaklı çalışan Google Ads'ten düzenli dönüşüm almak isteyen markalar.",
        features: [
          "Search + Display kampanya yapısı",
          "Satın alma niyeti yüksek anahtar kelime grupları",
          "A/B testli reklam metinleri",
          "Reklam uzantıları",
          "Gelişmiş negatif anahtar kelime yönetimi",
          "Teklif stratejileri (CPC / CPA)",
          "GA4 & dönüşüm entegrasyonu",
          "Haftalık optimizasyon & bütçe yönetimi",
          "Detaylı performans takibi",
          "Landing page öneri raporu",
        ],
        defaultPrice: 24900,
        priceSuffix: "/ tek seferlik",
        badge: "En çok tercih edilen",
        isCustomPrice: false,
      },
      {
        key: "GOOGLE_SCALE",
        name: "Reklam Performans+ Paketi",
        description: "Büyük ölçekli projeler için tam hizmet paketi.",
        features: [
          "Çok kampanyalı Search yapısı",
          "Display & remarketing kampanyaları",
          "Funnel bazlı Google Ads stratejisi",
          "Sürekli metin & copy testleri",
          "Günlük optimizasyon & ölçekleme",
          "ROAS / CPA odaklı bütçe yönetimi",
          "Özel dashboard & özel seviye raporlama",
          "Öncelikli destek & strateji görüşmeleri",
        ],
        defaultPrice: 45900,
        priceSuffix: "/ tek seferlik",
        isCustomPrice: false,
      },
    ],
  },
  {
    serviceKey: "TIKTOK_ADS",
    label: "TikTok Ads",
    tiers: [
      {
        key: "TIKTOK_START",
        name: "Keşif & Başlangıç Paketi",
        description: "TikTok Ads'e yeni başlayanlar veya küçük bütçeyle deneme yapmak isteyen markalar.",
        features: [
          "TikTok Business & Ads hesabı kurulumu",
          "Kampanya + temel funnel yapısı",
          "2-3 kreatif test süreci",
          "Temel hedef kitle ayarları",
          "Pixel & dönüşüm kontrolü",
          "Aylık performans raporu",
          "Aylık raporlama (Reklam ve Strateji)",
        ],
        defaultPrice: 13500,
        priceSuffix: "/ ay",
        isCustomPrice: false,
      },
      {
        key: "TIKTOK_GROWTH",
        name: "Satış Odaklı Büyüme Paketi",
        description: "Dijitalde var olmak yetmez; büyümek gerekir. Reklam süreçlerinizi ölçeklenebilir hale getirir.",
        features: [
          "Gelişmiş kampanya & funnel kurulumu",
          "A/B testli kreatif ve hedef kitle yapısı",
          "Haftalık optimizasyon ve bütçe yönetimi",
          "Meta Pixel & event optimizasyonu",
          "Detaylı performans takibi",
          "Haftalık not + aylık detaylı rapor",
          "2 haftada bir online toplantı",
        ],
        defaultPrice: 26900,
        priceSuffix: "/ ay",
        badge: "En çok tercih edilen",
        isCustomPrice: false,
      },
      {
        key: "TIKTOK_SCALE",
        name: "Reklam Performans+ Paketi",
        description: "ROAS & ölçekleme odaklı yüksek bütçeli, performans ve büyüme hedefleyen markalar için ideal paket.",
        features: [
          "Çok kampanyalı gelişmiş yapı",
          "Funnel bazlı reklam stratejisi",
          "Sürekli kreatif & copy testleri",
          "Günlük optimizasyon & ölçekleme",
          "ROAS ve CPA odaklı bütçe yönetimi",
          "Özel dashboard & ileri seviye raporlama",
        ],
        defaultPrice: null,
        priceSuffix: "",
        isCustomPrice: true,
      },
    ],
  },
  {
    serviceKey: "AMAZON_ADS",
    label: "Amazon Ads",
    tiers: [
      {
        key: "AMAZON_START",
        name: "Marketplace Start",
        description: "Amazon'da ilk reklam sistemini kurmak isteyen markalar için başlangıç paketi.",
        features: [
          "Amazon Ads hesap kontrolü",
          "Retail readiness mini denetimi",
          "10 anahtar kelime grubu",
          "Sponsored Products kurulumu",
          "Negatif kelime listesi",
          "İlk 14 gün optimizasyon",
          "Başlangıç performans raporu",
        ],
        defaultPrice: 16900,
        priceSuffix: "/ proje",
        isCustomPrice: false,
      },
      {
        key: "AMAZON_GROWTH",
        name: "Amazon Growth Engine",
        description: "Satış, karlılık ve pazar payını birlikte büyütmek isteyen markalar için ana büyüme sistemi.",
        features: [
          "Full kampanya mimarisi",
          "Sponsored Products + Brands + Display",
          "Rakip ASIN hedefleme",
          "Search term mining",
          "ACOS / TACOS dashboard",
          "Haftalık bütçe optimizasyonu",
          "Kreatif & ürün sayfası önerileri",
          "Aylık strateji görüşmesi",
          "Detaylı performans raporu",
        ],
        defaultPrice: 29900,
        priceSuffix: "/ ay",
        badge: "En karlı ölçek",
        isCustomPrice: false,
      },
      {
        key: "AMAZON_SCALE",
        name: "Category Domination",
        description: "Bir kategoride görünürlüğünü agresif ama kontrollü büyütmek isteyen markalar için.",
        features: [
          "Kategori ve rakip haritası",
          "Çoklu ASIN kampanya yapısı",
          "Brand defense + conquest stratejisi",
          "Ürün sayfası dönüşüm danışmanlığı",
          "Store & Sponsored Brands kurgusu",
          "Gelişmiş remarketing",
          "Haftalık strateji sprinti",
          "Yönetim kuruluna uygun raporlama",
        ],
        defaultPrice: null,
        priceSuffix: "",
        isCustomPrice: true,
      },
    ],
  },
  {
    serviceKey: "TECHNICAL_SUPPORT",
    label: "Web Teknik Destek",
    tiers: [
      {
        key: "TECH_START",
        name: "Başlangıç Destek Paketi",
        description: "Her ay 2 kez teknik destek talebinde bulunabilir ve sitenizin 5 sayfasında güncelleme yaptırabilirsiniz.",
        features: [
          "Ayda 2 kez destek talebi",
          "5 adet sayfa güncelleme",
          "Düzenli bakım & kontroller",
          "Telefon ve e-posta desteği",
        ],
        defaultPrice: 9900,
        priceSuffix: "+ KDV",
        isCustomPrice: false,
      },
      {
        key: "TECH_PRO",
        name: "Profesyonel Destek Paketi",
        description: "Her ay 5 kez teknik destek talebinde bulunabilir ve sitenizin 10 sayfasında güncelleme yaptırabilirsiniz.",
        features: [
          "Ayda 5 kez destek talebi",
          "10 adet sayfa güncelleme",
          "Düzenli bakım & kontroller",
          "Telefon, e-posta ve online toplantı",
        ],
        defaultPrice: 26900,
        priceSuffix: "/ ay",
        badge: "En çok tercih edilen",
        isCustomPrice: false,
      },
      {
        key: "TECH_SCALE",
        name: "İleri Seviye Destek Paketi",
        description: "Her ay 7 kez teknik destek talebinde bulunabilir ve sitenizin 15 sayfasında güncelleme yaptırabilirsiniz.",
        features: [
          "Ayda 7 kez destek talebi",
          "15 adet sayfa güncelleme",
          "Düzenli bakım & kontroller",
          "Telefon, e-posta ve online toplantı",
        ],
        defaultPrice: null,
        priceSuffix: "",
        isCustomPrice: true,
      },
    ],
  },
  {
    serviceKey: "SEO_AUDIT",
    label: "SEO Denetimi",
    tiers: [
      {
        key: "SEO_START",
        name: "SEO Başlangıç Paketi",
        description: "Teknik audit veya başlangıç seviyesinde SEO desteği isteyen markalar.",
        features: [
          "HTML site takibi",
          "SEO denetim raporu (aylık)",
          "Rakip SEO analizi",
          "Sayfa hızı optimizasyonu",
          "Tarama ve index denetimi",
          "Search Console hata kontrolü",
          "Öncelikli aksiyon listesi",
        ],
        defaultPrice: 13500,
        priceSuffix: "/ ay",
        isCustomPrice: false,
      },
      {
        key: "SEO_PRO",
        name: "SEO Gelişmiş Paketi",
        description: "Düzenli SEO takibi, teknik iyileştirme ve büyüme isteyen markalar için.",
        features: [
          "Gelişmiş SEO takibi",
          "SEO denetim raporu (haftalık)",
          "Rakip SEO analizi",
          "Teknik optimizasyon",
          "Tarama ve index denetimi",
          "İçerik teknik uyumluluğu",
          "Site hızı optimizasyonu",
          "Schema & Rich Snippet önerileri",
          "Aylık aksiyon planı",
        ],
        defaultPrice: 26900,
        priceSuffix: "/ ay",
        badge: "En çok tercih edilen",
        isCustomPrice: false,
      },
      {
        key: "SEO_WHITE_LABEL",
        name: "White Label",
        description: "ROAS & ölçekleme odaklı teknik destek, performans ve büyüme hedefleyen markalar için özel paket.",
        features: [
          "Ajanslara özel çalışma",
          "White label raporlar",
          "Markasız teknik doküman",
          "Gelişmiş teknik analiz",
          "SEO destek reçetesi",
          "Öncelikli danışmanlık",
          "Aylık koordinasyon",
        ],
        defaultPrice: null,
        priceSuffix: "",
        isCustomPrice: true,
      },
    ],
  },
  {
    serviceKey: "MOBILE_APP",
    label: "Mobil Uygulama",
    tiers: [
      {
        key: "MOBILE_START",
        name: "Başlangıç App Paketi",
        description: "Fikrini hızlıca test etmek isteyen markalar için yalın mobil ürün başlangıcı.",
        features: [
          "4-6 temel ekran tasarımı",
          "Kullanıcı giriş / kayıt akışı",
          "Basit yönetim paneli",
          "Tek platform yayın hazırlığı",
          "Temel event ölçümleme",
        ],
        defaultPrice: 19900,
        priceSuffix: "/ proje",
        isCustomPrice: false,
      },
      {
        key: "MOBILE_GROWTH",
        name: "Ürünleşen App Paketi",
        description: "İlk sürümden ciddi ürüne geçmek isteyen ekipler için panel, API ve büyüme altyapısı.",
        features: [
          "UX akışı ve ekran mimarisi",
          "iOS / Android hibrit geliştirme",
          "Admin panel ve API katmanı",
          "Push bildirim altyapısı",
          "App Store / Play Store yayına hazırlık",
          "Crash, event ve funnel takibi",
          "2 sprint iyileştirme desteği",
        ],
        defaultPrice: 44900,
        priceSuffix: "/ proje",
        badge: "En Çok Tercih Edilen",
        isCustomPrice: false,
      },
      {
        key: "MOBILE_SCALE",
        name: "Scale App Paketi",
        description: "Yoğun kullanıcı, özel entegrasyon ve uzun vadeli ürün geliştirme ihtiyacı olan markalar için.",
        features: [
          "Özel mobil ürün stratejisi",
          "Çoklu rol ve yetki yönetimi",
          "Gelişmiş entegrasyon mimarisi",
          "Performans ve güvenlik optimizasyonu",
          "Sürüm yol haritası ve sprint yönetimi",
          "Ürün analitiği ve büyüme raporu",
        ],
        defaultPrice: null,
        priceSuffix: "",
        isCustomPrice: true,
      },
    ],
  },
  {
    serviceKey: "LANDING_PAGE",
    label: "Landing Page / UI-UX",
    tiers: [
      {
        key: "LP_DESIGN",
        name: "Tasarım Paketi",
        description: "Yeni başlayanlar ve küçük işletmeler için ideal paket.",
        features: [
          "5 sayfa UI tasarımı",
          "Responsive (mobil + desktop)",
          "Basit marka rehberi",
          "2 revize hakkı",
          "Kaynak tasarım dosyaları",
          "Hızlı destek (48 saat)",
          "Etkileşim akışı",
        ],
        defaultPrice: 12500,
        priceSuffix: "/ proje",
        isCustomPrice: false,
      },
      {
        key: "LP_PRO",
        name: "Tasarım & Akış Paketi",
        description: "Büyüyen işletmeler için kapsamlı tasarım çözümü.",
        features: [
          "15 sayfa UI/UX tasarımı",
          "Responsive + tablet optimizasyon",
          "Detaylı marka kimliği paketi",
          "Kullanıcı akış haritası",
          "5 revize hakkı",
          "Tüm kaynak dosyalar",
          "Öncelikli destek (24 saat)",
          "1 ay ücretsiz güncelleme",
          "Etkileşim akışı",
        ],
        defaultPrice: 24900,
        priceSuffix: "/ tek seferlik",
        badge: "En çok tercih edilen",
        isCustomPrice: false,
      },
      {
        key: "LP_SCALE",
        name: "Tasarım & Akış+ Paketi",
        description: "Büyük ölçekli projeler için tam hizmet paketi.",
        features: [
          "Sınırsız sayfa tasarımı",
          "Tüm platformlar için optimizasyon",
          "Kapsamlı design system",
          "Akış testi ve kullanım kontrolleri",
          "Sınırsız revize",
          "Animasyon ve mikroetkileşimler",
          "7/24 özel destek",
          "3 ay ücretsiz güncelleme",
        ],
        defaultPrice: 45900,
        priceSuffix: "/ tek seferlik",
        isCustomPrice: false,
      },
    ],
  },
  {
    serviceKey: "WEB_APP",
    label: "Web Uygulama",
    tiers: [
      {
        key: "WEB_CUSTOM",
        name: "Özel Web Uygulaması",
        description: "İş süreçlerini dijitale taşıyan, ölçeklenebilir ve sürdürülebilir sistemler.",
        features: [
          "Gereksinim analizi & keşif",
          "Mimari & tasarım",
          "Geliştirme & test",
          "Yayın & ölçekleme",
          "Proje sonrası teknik destek",
        ],
        defaultPrice: null,
        priceSuffix: "",
        isCustomPrice: true,
      },
    ],
  },
  {
    serviceKey: "WEB_MOBILE_DESIGN",
    label: "Web & Mobil Tasarım",
    tiers: [
      {
        key: "DESIGN_CUSTOM",
        name: "Özel Tasarım Projesi",
        description: "Marka kimliğini, görsel sistemi ve modern arayüz dilini tek akışta kurun.",
        features: [
          "UI/UX tasarım",
          "Responsive tasarım",
          "Design system",
          "Prototip & etkileşim akışı",
          "Kaynak dosyalar",
        ],
        defaultPrice: null,
        priceSuffix: "",
        isCustomPrice: true,
      },
    ],
  },
];

export const CATALOG_BY_SERVICE_KEY: Record<string, ServiceCatalogEntry> = Object.fromEntries(
  SERVICE_CATALOG.map((entry) => [entry.serviceKey, entry]),
);

export function getTierByKey(serviceKey: string, tierKey: string): PackageTier | null {
  return CATALOG_BY_SERVICE_KEY[serviceKey]?.tiers.find((t) => t.key === tierKey) ?? null;
}

export function formatCatalogPrice(tier: PackageTier): string {
  if (tier.isCustomPrice || tier.defaultPrice === null) return "Özel Fiyat";
  return `${tier.defaultPrice.toLocaleString("tr-TR")} ₺ ${tier.priceSuffix}`.trim();
}
