-- AlterEnum
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'TIKTOK_ADS_CAMPAIGN_APPROVAL';

-- AlterEnum
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'TIKTOK_ADS_VIDEO_CREATIVE_APPROVAL';

-- AlterEnum
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'TIKTOK_ADS_HOOK_TEST_APPROVAL';

-- AlterEnum
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'TIKTOK_ADS_UGC_SCRIPT_APPROVAL';

-- AlterEnum
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'TIKTOK_ADS_BUDGET_CHANGE_APPROVAL';

-- AlterEnum
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'TIKTOK_ADS_REPORT_ACKNOWLEDGEMENT';
