ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'SOCIAL_MEDIA_POST_APPROVAL';
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'SOCIAL_MEDIA_CREATIVE_APPROVAL';
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'SOCIAL_MEDIA_CAPTION_APPROVAL';
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'SOCIAL_MEDIA_CALENDAR_APPROVAL';
ALTER TYPE "MetaAdsApprovalType" ADD VALUE IF NOT EXISTS 'SOCIAL_MEDIA_REPORT_ACKNOWLEDGEMENT';
